INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'On-Site Dr. Visit');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'Dr. Visit');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'Surgery');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, '9-1-1');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'Misc');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'Care Conference');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'No Show');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'No Call');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'Behavior Issue');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'Misc.');
INSERT INTO `tbl_event_definition` (`id_space`, `title`) VALUES (1, 'Hospitalization');
