INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Soy Sauce', 'All Types');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Walnuts', 'Raw, or cooked');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Chocolate', 'Any variety');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Shellfish', 'All types');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Lactose', 'Dairy');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Milk', 'Dairy');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Steak', 'Meat');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Latex', 'any variety');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Gluten', 'Gluten Intolerence');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Seasonal', 'Hay Fever');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Lemons', 'Anything with Lemon');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Vinegar', 'All types');
INSERT INTO `tbl_allergen` (`id_space`, `title`, `description`) VALUES (1, 'Pork', 'All pork products');
