INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Accountant');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'ALWP');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Attorney');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Attorney-In-Fact');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Brother');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Brother POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Brother-in-Law');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Caregiver');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Caretaker');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Case Manager');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Conservator');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Cousin');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Daughter');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Daughter POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Daughter-in-Law');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Designated POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Doctor');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Durable POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Father');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Fiduciary');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Financial POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Foster Daughter');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Friend');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Friend POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Grand Daughter');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Grand Niece');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Grand Son');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Great Nephew');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Guardian');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Husband');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Mother');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Neighbor');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Nephew');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Nephew POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Nephew-in-Law');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Niece');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Niece-in-Law');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Payee');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Public Guardian');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Relative');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Significant Other');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Sister');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Sister POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Sister-in-Law');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Son');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Son Health POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Son POA');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Son POA Trustee');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Son-in-Law');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Spouse');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'SSC');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Step Daughter');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Step Father');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Step Son');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Trust Office');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Trustee');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Unknown');
INSERT INTO `tbl_relationship` (`id_space`, `title`) VALUES (1, 'Wife');
