INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Allergy and Immunology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Anesthesiology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Dermatology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Diagnostic Radiology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Emergency Medicine');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Family Medicine');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Internal Medicine');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Endocrinology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Gastroenterology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Geratiric Medicine');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Hematology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Interventional Cardiology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Medical Oncology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Nephrology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Rheumatology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Medical Genetics');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Neurology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Nuclear Medicine');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Obstetrics and Gynecology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Ophthalmology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Orthopaedic Surgery');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Otolaryngology - Head and Neck Surgery');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Pathology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Physical Medicine and Rehabilitation');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Plastic Surgery');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Preventive Medicine');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Psychiatry');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Radiology');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Surgery');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Thoracic Surgery');
INSERT INTO `tbl_speciality` (`id_space`, `title`) VALUES  (1, 'Urology');
