INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Mechanical Soft');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Puree');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Diabetic');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'No Dairy');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Special Request');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'No Salt Diet');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Regular Diet');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Chopped Diet');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Low sodium (salt)');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Lactose Intolerant');
INSERT INTO `tbl_diet` (`id_space`, `title`) VALUES (1, 'Thick Liquid');
